# Generated by Django 3.0.5 on 2021-03-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0002_auto_20210308_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='allowed_games',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='player',
            name='instructors',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
