# Generated by Django 3.0.5 on 2021-03-08 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0003_auto_20210308_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='allowed_games',
        ),
        migrations.RemoveField(
            model_name='player',
            name='backorder',
        ),
        migrations.RemoveField(
            model_name='player',
            name='current_game',
        ),
        migrations.RemoveField(
            model_name='player',
            name='downstream_player',
        ),
        migrations.RemoveField(
            model_name='player',
            name='instructors',
        ),
        migrations.RemoveField(
            model_name='player',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='player',
            name='upstream_player',
        ),
    ]
