# Generated by Django 3.0.5 on 2021-03-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0005_auto_20210308_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='games_managing',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='instructor',
            name='my_default_game',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='instructor',
            name='my_players',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='instructor',
            name='my_plots',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='player',
            name='allowed_games',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='player',
            name='instructors',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
