# Generated by Django 3.0.5 on 2021-03-08 23:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0007_auto_20210308_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='public_id')),
                ('session_length', models.IntegerField(default=0)),
                ('distributor_present', models.BooleanField(default=False)),
                ('wholesaler_present', models.BooleanField(default=False)),
                ('holding_cost', models.FloatField(default=0.0)),
                ('backlog_cost', models.FloatField(default=0.0)),
                ('active', models.BooleanField(default=False)),
                ('info_sharing', models.BooleanField(default=False)),
                ('info_delay', models.IntegerField(default=2)),
                ('rounds_completed', models.IntegerField(default=0)),
                ('is_default_game', models.BooleanField(default=False)),
                ('starting_inventory', models.IntegerField(default=12)),
                ('player_weeks', models.CharField(max_length=4)),
                ('demand_pattern', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='games_demand_pattern', to='beer.DemandPattern')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors_game', to='beer.Instructor')),
                ('player', models.ManyToManyField(related_name='players_game', to='beer.Player')),
            ],
            options={
                'verbose_name': 'game',
                'verbose_name_plural': 'games',
            },
        ),
    ]
