# Generated by Django 3.0.5 on 2021-03-09 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0009_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
